# Generated by Django 4.1.5 on 2023-01-19 09:47

from django.conf import settings
import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MainPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='UserPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.IntegerField()),
                ('created_at', models.DateField(auto_now_add=True)),
                ('updated_at', models.DateField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PostLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=200)),
                ('geo_location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('main_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lay_travel.mainplace')),
            ],
        ),
        migrations.AddField(
            model_name='mainplace',
            name='post_information',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lay_travel.userpost'),
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_post', models.ImageField(upload_to='images/')),
                ('main_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lay_travel.mainplace')),
            ],
        ),
    ]
