# Generated by Django 4.1.5 on 2023-01-19 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainplace',
            old_name='name',
            new_name='main_place_name',
        ),
    ]
