# Generated by Django 4.1.5 on 2023-01-20 10:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0002_rename_name_mainplace_main_place_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mainplace',
            old_name='main_place_name',
            new_name='place_name',
        ),
        migrations.RemoveField(
            model_name='mainplace',
            name='post_information',
        ),
        migrations.AddField(
            model_name='userpost',
            name='main_place',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='lay_travel.mainplace'),
        ),
    ]
