# Generated by Django 4.1.5 on 2023-01-20 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0005_rename_main_place_mainplace_user_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='main_place_id',
            field=models.IntegerField(default=0),
        ),
    ]
