# Generated by Django 4.1.5 on 2023-01-20 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0006_userpost_main_place_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mainplace',
            name='user_post',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='main_place_id',
        ),
        migrations.AddField(
            model_name='userpost',
            name='main_place',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='lay_travel.mainplace'),
        ),
    ]
