# Generated by Django 4.1.5 on 2023-01-20 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0007_remove_mainplace_user_post_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpost',
            name='main_place',
            field=models.IntegerField(default=0),
        ),
    ]
