# Generated by Django 4.1.5 on 2023-01-20 13:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0008_alter_userpost_main_place'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userpost',
            old_name='main_place',
            new_name='main_place_id',
        ),
    ]
