# Generated by Django 4.1.5 on 2023-01-23 10:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0013_alter_image_post_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='post_location',
        ),
    ]
