# Generated by Django 4.1.5 on 2023-04-28 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0015_image_post_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpost',
            name='package_name',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='userpost',
            name='main_place_id',
            field=models.IntegerField(null=True),
        ),
    ]
