# Generated by Django 4.1.5 on 2023-05-16 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0016_userpost_package_name_alter_userpost_main_place_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=200)),
                ('main_place_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lay_travel.mainplace')),
            ],
        ),
    ]
