# Generated by Django 4.1.5 on 2023-05-16 08:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0017_package'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='main_place_id',
            new_name='main_place',
        ),
    ]
