# Generated by Django 4.1.5 on 2023-05-16 11:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0018_rename_main_place_id_package_main_place'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackagePlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('main_place', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lay_travel.mainplace')),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lay_travel.package')),
            ],
        ),
    ]
