# Generated by Django 4.1.5 on 2023-05-16 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0019_packageplace'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postlocation',
            name='main_place',
        ),
        migrations.RemoveField(
            model_name='userpost',
            name='package_name',
        ),
        migrations.AddField(
            model_name='postlocation',
            name='user_post',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='lay_travel.userpost'),
            preserve_default=False,
        ),
    ]
