# Generated by Django 4.1.5 on 2023-05-16 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lay_travel', '0020_remove_postlocation_main_place_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='main_place',
        ),
    ]
